[package]
name = "libadamant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stivale-boot = "0.2.6"
libc = { version = "0.2.119", default-features = false }
